blueprint:
  name: Timer-Based Lighting Automation (v2026.01.02.09.10)
  author: Dima Tokar
  source_url: https://github.com/dimatx/home-assistant/blob/main/blueprints/timer_driven_lighting_blueprint.yaml
  homeassistant:
    min_version: 2025.1.0
  description: >
    Advanced lighting automation that uses a Timer helper. 
    Includes logic to prevent "stuck on" states when occupancy clears after a timer expires,
    increased trace history, and optional debug logging.
  domain: automation

# Override default trace limit to 15 for better troubleshooting
stored_traces: 15

  input:
    configuration:
      name: Configuration
      icon: mdi:cogs
      collapsed: false
      input:
        timer_entity:
          name: Timer Entity
          description: The timer helper that tracks the duration for the lights to stay on.
          selector:
            entity:
              domain: timer
        lights:
          name: Lights to Control
          description: The lights, areas, devices, or labels to manage.
          selector:
            target:
              entity:
                domain: light
        trigger_entities:
          name: Trigger Entities
          description: Sensors or entities that trigger the timer.
          selector:
            entity:
              multiple: true
        trigger_states:
          name: Trigger States
          description: Comma-separated list of states that trigger the timer (e.g., 'on, open').
          default: "on"
          selector:
            text:
    condition_settings:
      name: Conditions
      icon: mdi:filter-variant
      collapsed: false
      input:
        global_conditions:
          name: Global Conditions
          description: Conditions that must be met for ANY action to run.
          default: []
          selector:
            condition:
        turn_on_conditions:
          name: Turn ON Conditions
          description: Additional conditions specifically to turn the lights ON.
          default: []
          selector:
            condition:
        turn_off_conditions:
          name: Turn OFF Conditions
          description: Additional conditions specifically to turn the lights OFF.
          default: []
          selector:
            condition:
    other_settings:
      name: Other Settings
      icon: mdi:timer-cog
      collapsed: true
      input:
        timer_duration:
          name: Timer Duration (Optional)
          description: "Overrides the default duration in the timer helper."
          default: ""
          selector:
            duration:
        debug_mode:
          name: Enable Debug Mode
          description: "Logs logic decisions to the Logbook. Does not affect performance."
          default: false
          selector:
            boolean:

mode: restart

variables:
  trigger_states_input: !input trigger_states
  trigger_states_list: "{{ (trigger_states_input | string).split(',') | map('trim') | list }}"
  timer_duration_value: !input timer_duration
  debug_enabled: !input debug_mode

trigger:
  - platform: state
    entity_id: !input timer_entity
    from: idle
    to: active
    id: timer_active
    alias: "Timer started (Active)"
  - platform: state
    entity_id: !input timer_entity
    to: idle
    id: timer_idle
    alias: "Timer finished (Idle)"
  - platform: state
    entity_id: !input trigger_entities
    id: entity_triggered
    alias: "Activity sensor triggered"

condition:
  - condition: and
    conditions: !input global_conditions
    alias: "Check Global Conditions"

action:
  # Initial Debug Logging - Fired only if Debug Mode is ON
  - if:
      - condition: template
        value_template: "{{ debug_enabled }}"
    then:
      - action: logbook.log
        data:
          name: "Debug: {{ this.entity_id }}"
          message: "Triggered by {{ trigger.to_state.entity_id if trigger.to_state is defined else 'Timer' }} transitioning to {{ trigger.to_state.state if trigger.to_state is defined else 'Idle' }}"

  - choose:
      # 1. Start/Restart Timer on activity
      - alias: "Activity detected: Start/Restart Timer"
        conditions:
          - condition: trigger
            id: entity_triggered
          - condition: template
            value_template: "{{ trigger.to_state.state in trigger_states_list }}"
            alias: "Check if state matches Trigger States"
        sequence:
          - choose:
              - alias: "Use Override Duration"
                conditions:
                  - condition: template
                    value_template: "{{ timer_duration_value != '' and timer_duration_value != none }}"
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity
                      duration: !input timer_duration
              - alias: "Use Timer Default Duration"
                conditions: []
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity

      # 2. Turn Lights ON
      - alias: "Timer Active: Turn Lights ON"
        conditions:
          - condition: trigger
            id: timer_active
          - condition: and
            conditions: !input turn_on_conditions
            alias: "Check Turn ON Conditions"
        sequence:
          - action: light.turn_on
            target: !input lights

      # 3. Turn Lights OFF
      - alias: "Timer Idle: Turn Lights OFF"
        conditions:
          - condition: trigger
            id: timer_idle
          - condition: and
            conditions: !input turn_off_conditions
            alias: "Check Turn OFF Conditions"
        sequence:
          - action: light.turn_off
            target: !input lights

      # 4. Turn Lights OFF when trigger entity changes and timer is already idle
      - alias: "Activity detected & Timer Idle: Turn Lights OFF"
        conditions:
          - condition: trigger
            id: entity_triggered
          - condition: state
            entity_id: !input timer_entity
            state: idle
          - condition: and
            conditions: !input turn_off_conditions
            alias: "Check Turn OFF Conditions"
        sequence:
          - action: light.turn_off
            target: !input lights