blueprint:
  name: Timer-Based Lighting Automation (v2026.01.26.13.26)
  author: Dima Tokar
  source_url: https://github.com/dimatx/home-assistant/blob/main/blueprints/timer_driven_lighting_blueprint.yaml
  homeassistant:
    min_version: 2025.1.0
  description: >
    Turn on lights based on a trigger (e.g., motion) and keep them on using a Timer helper.
    The timer restarts with each new trigger event. Lights turn off when the timer finishes.
    Optionally restart the timer when any controlled light is turned on (manually or by other automations).
    Supports optional conditions for turning on/off and works with Lights, Areas, Devices, and Labels.
  domain: automation
  input:
    configuration:
      name: Configuration
      icon: mdi:cogs
      collapsed: false
      input:
        timer_entity:
          name: Timer Entity
          description: The timer helper that tracks the duration for the lights to stay on.
          selector:
            entity:
              domain: timer
        lights:
          name: Lights to Control
          description: The lights, areas, devices, or labels to manage.
          selector:
            target:
              entity:
                domain: light
        trigger_entities:
          name: Trigger Entities
          description: Sensors or entities (e.g., motion sensors, door sensors) that trigger the timer.
          selector:
            entity:
              multiple: true
        trigger_states:
          name: Trigger States
          description: Comma-separated list of states that trigger the timer (e.g., 'on, open'). Defaults to 'on'.
          default: "on"
          selector:
            text:
    condition_settings:
      name: Conditions
      icon: mdi:filter-variant
      collapsed: false
      input:
        global_conditions:
          name: Global Conditions
          description: Conditions that must be met for ANY action (turn on or off) to run.
          default: []
          selector:
            condition:
        turn_on_conditions:
          name: Turn ON Conditions
          description: Additional conditions that must be met specifically to turn the lights ON.
          default: []
          selector:
            condition:
        turn_off_conditions:
          name: Turn OFF Conditions
          description: Additional conditions that must be met specifically to turn the lights OFF. In order for the automation to retrigger when the OFF condition is no longer blocking, it must also be listed as a trigger entity.
          default: []
          selector:
            condition:
    other_settings:
      name: Other Settings
      icon: mdi:timer-cog
      collapsed: true
      input:
        timer_duration:
          name: Timer Duration (Optional)
          description: "If specified, this duration overrides the default duration configured in the timer helper."
          default: ""
          selector:
            duration:
        restart_on_light_on:
          name: Restart Timer on Light On
          description: "If enabled, the timer will restart whenever any of the monitored lights (below) is turned on (manually or by other automations)."
          default: false
          selector:
            boolean:
        restart_on_light_on_entities:
          name: Lights to Monitor
          description: "Specify which light entities should restart the timer when turned on. Only used if 'Restart Timer on Light On' is enabled."
          default: []
          selector:
            entity:
              domain: light
              multiple: true
        timer_only_trigger_entities:
          name: Timer-Only Trigger Entities
          description: "Trigger entities listed here will restart the timer but will NOT turn on lights if they're off. Useful for mmWave sensors that should only maintain lights, not activate them. These entities must also be listed in 'Trigger Entities' above."
          default: []
          selector:
            entity:
              multiple: true
        debug_mode:
          name: Debug Mode
          description: "If enabled, debug information will be logged to the system log."
          default: false
          selector:
            boolean:

mode: restart

variables:
  trigger_states_input: !input trigger_states
  trigger_states_list: "{{ (trigger_states_input | string).split(',') | map('trim') | list }}"
  timer_duration_value: !input timer_duration
  restart_on_light_on: !input restart_on_light_on
  timer_only_triggers: !input timer_only_trigger_entities
  debug_mode: !input debug_mode

trigger:
  - platform: state
    entity_id: !input timer_entity
    from: idle
    to: active
    id: timer_active
    alias: "Timer started (Active)"
  - platform: state
    entity_id: !input timer_entity
    to: idle
    id: timer_idle
    alias: "Timer finished (Idle)"
  - platform: state
    entity_id: !input trigger_entities
    id: entity_triggered
    alias: "Activity sensor triggered"
  - platform: state
    entity_id: !input restart_on_light_on_entities
    from: "off"
    to: "on"
    id: light_turned_on
    alias: "Light turned on"

condition:
  - condition: and
    conditions: !input global_conditions
    alias: "Check Global Conditions"

action:
  - if:
      - condition: template
        value_template: "{{ debug_mode }}"
    then:
      - action: system_log.write
        data:
          message: "Blueprint Debug: Triggered by {{ trigger.id if trigger else 'unknown' }}. Trigger data: {{ trigger }}"
          level: info
          logger: blueprints.timer_driven_lighting
  - choose:
      # 1. Start/Restart Timer on activity
      - alias: "Activity detected: Start/Restart Timer"
        conditions:
          - condition: trigger
            id: entity_triggered
          - condition: template
            value_template: "{{ trigger.to_state.state in trigger_states_list }}"
            alias: "Check if state matches Trigger States"
          # Only start timer if it's already active OR turn_on_conditions are met.
          # Note: global_conditions are already checked at the automation top-level.
          - condition: or
            conditions:
              - condition: state
                entity_id: !input timer_entity
                state: active
              - condition: and
                conditions: !input turn_on_conditions
        sequence:
          # Turn on lights FIRST if timer is idle (prevents race condition where
          # rapid triggers cancel the timer_active event before lights turn on)
          # Skip turning on lights if this trigger is in the timer-only list
          - if:
              - condition: state
                entity_id: !input timer_entity
                state: idle
              - condition: template
                value_template: "{{ trigger.entity_id not in timer_only_triggers }}"
                alias: "Check if trigger is NOT timer-only"
            then:
              - action: light.turn_on
                target: !input lights
          # Then start/restart the timer
          - choose:
              # Use the override duration if it's set
              - alias: "Use Override Duration"
                conditions:
                  - condition: template
                    value_template: "{{ timer_duration_value != '' and timer_duration_value != none }}"
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity
                      duration: !input timer_duration
              - alias: "Use Timer Default Duration"
                conditions: []
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity

      # 1b. Restart Timer when light is turned on externally
      - alias: "Light turned on: Restart Timer"
        conditions:
          - condition: trigger
            id: light_turned_on
          - condition: template
            value_template: "{{ restart_on_light_on }}"
            alias: "Check if restart on light-on is enabled"
          - condition: template
            value_template: "{{ trigger.to_state.context.id != this.context.id }}"
            alias: "Prevent self-triggering (external change only)"
        sequence:
          - choose:
              # Use the override duration if it's set
              - alias: "Use Override Duration"
                conditions:
                  - condition: template
                    value_template: "{{ timer_duration_value != '' and timer_duration_value != none }}"
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity
                      duration: !input timer_duration
              - alias: "Use Timer Default Duration"
                conditions: []
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity

      # 2. Turn Lights ON
      - alias: "Timer Active: Turn Lights ON"
        conditions:
          - condition: trigger
            id: timer_active
          - condition: and
            conditions: !input turn_on_conditions
            alias: "Check Turn ON Conditions"
        sequence:
          - action: light.turn_on
            target: !input lights

      # 3. Turn Lights OFF
      - alias: "Timer Idle: Turn Lights OFF"
        conditions:
          - condition: trigger
            id: timer_idle
          - condition: and
            conditions: !input turn_off_conditions
            alias: "Check Turn OFF Conditions"
        sequence:
          - action: light.turn_off
            target: !input lights

      # 4. Turn Lights OFF when trigger entity changes and timer is already idle
      # This handles the case where the timer expired but lights stayed ON due to a condition (e.g. occupancy),
      # and now that condition has cleared.
      - alias: "Activity detected & Timer Idle: Turn Lights OFF"
        conditions:
          - condition: trigger
            id: entity_triggered
          - condition: state
            entity_id: !input timer_entity
            state: idle
          - condition: and
            conditions: !input turn_off_conditions
            alias: "Check Turn OFF Conditions"
        sequence:
          - action: light.turn_off
            target: !input lights