blueprint:
  name: Timer-Based Lighting Automation (v2025.12.25.17.47)
  author: Dima Tokar
  source_url: https://github.com/dimatx/home-assistant/blob/main/blueprints/timer_driven_lighting_blueprint.yaml
  homeassistant:
    min_version: 2025.1.0
  description: >
    Automatically controls lights based on a timer and trigger entities.
    Compatible with Entities, Devices, Areas, and Labels.
  domain: automation
  input:
    configuration:
      name: Configuration
      icon: mdi:cogs
      collapsed: false
      input:
        timer_entity:
          name: Timer Entity
          selector:
            entity:
              domain: timer
        lights:
          name: Lights to Control
          selector:
            target:
              entity:
                domain: light
        trigger_entities:
          name: Trigger Entities
          selector:
            entity:
              multiple: true
        trigger_states:
          name: Trigger States
          default: "on"
          selector:
            text:
    condition_settings:
      name: Conditions
      icon: mdi:filter-variant
      collapsed: false
      input:
        global_conditions:
          name: Global Conditions
          default: []
          selector:
            condition:
        turn_on_conditions:
          name: Turn ON Conditions
          default: []
          selector:
            condition:
        turn_off_conditions:
          name: Turn OFF Conditions
          default: []
          selector:
            condition:
    other_settings:
      name: Other Settings
      icon: mdi:timer-cog
      collapsed: true
      input:
        timer_duration:
          name: Timer Duration (Optional)
          description: "Leave empty to use the timer helper's default duration."
          default: ""
          selector:
            duration:

mode: restart

variables:
  trigger_states_input: !input trigger_states
  trigger_states_list: "{{ (trigger_states_input | string).split(',') | map('trim') | list }}"
  timer_duration_value: !input timer_duration

trigger:
  - platform: state
    entity_id: !input timer_entity
    from: idle
    to: active
    id: timer_active
  - platform: state
    entity_id: !input timer_entity
    to: idle
    id: timer_idle
  - platform: state
    entity_id: !input trigger_entities
    id: entity_triggered

condition:
  - condition: and
    conditions: !input global_conditions

action:
  - choose:
      # 1. Start/Restart Timer on activity
      - conditions:
          - condition: trigger
            id: entity_triggered
          - condition: template
            value_template: "{{ trigger.to_state.state in trigger_states_list }}"
        sequence:
          - choose:
              # Use the override duration if it's set
              - conditions:
                  - condition: template
                    value_template: "{{ timer_duration_value != '' and timer_duration_value != none }}"
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity
                      duration: !input timer_duration
            default:
              # Otherwise, start the timer with its own internal default
              - action: timer.start
                data:
                  entity_id: !input timer_entity

      # 2. Turn Lights ON
      - conditions:
          - condition: trigger
            id: timer_active
          - condition: and
            conditions: !input turn_on_conditions
        sequence:
          - action: light.turn_on
            target: !input lights

      # 3. Turn Lights OFF
      - conditions:
          - condition: trigger
            id: timer_idle
          - condition: and
            conditions: !input turn_off_conditions
        sequence:
          - action: light.turn_off
            target: !input lights