blueprint:
  name: Timer-Based Lighting Automation (v2025.12.26.15.33)
  author: Dima Tokar
  source_url: https://github.com/dimatx/home-assistant/blob/main/blueprints/timer_driven_lighting_blueprint.yaml
  homeassistant:
    min_version: 2025.1.0
  description: >
    Turn on lights based on a trigger (e.g., motion) and keep them on using a Timer helper.
    The timer restarts with each new trigger event. Lights turn off when the timer finishes.
    Supports optional conditions for turning on/off and works with Lights, Areas, Devices, and Labels.
  domain: automation
  input:
    configuration:
      name: Configuration
      icon: mdi:cogs
      collapsed: false
      input:
        timer_entity:
          name: Timer Entity
          description: The timer helper that tracks the duration for the lights to stay on.
          selector:
            entity:
              domain: timer
        lights:
          name: Lights to Control
          description: The lights, areas, devices, or labels to manage.
          selector:
            target:
              entity:
                domain: light
        trigger_entities:
          name: Trigger Entities
          description: Sensors or entities (e.g., motion sensors, door sensors) that trigger the timer.
          selector:
            entity:
              multiple: true
        trigger_states:
          name: Trigger States
          description: Comma-separated list of states that trigger the timer (e.g., 'on, open'). Defaults to 'on'.
          default: "on"
          selector:
            text:
    condition_settings:
      name: Conditions
      icon: mdi:filter-variant
      collapsed: false
      input:
        global_conditions:
          name: Global Conditions
          description: Conditions that must be met for ANY action (turn on or off) to run.
          default: []
          selector:
            condition:
        turn_on_conditions:
          name: Turn ON Conditions
          description: Additional conditions that must be met specifically to turn the lights ON.
          default: []
          selector:
            condition:
        turn_off_conditions:
          name: Turn OFF Conditions
          description: Additional conditions that must be met specifically to turn the lights OFF.
          default: []
          selector:
            condition:
    other_settings:
      name: Other Settings
      icon: mdi:timer-cog
      collapsed: true
      input:
        timer_duration:
          name: Timer Duration (Optional)
          description: "If specified, this duration overrides the default duration configured in the timer helper."
          default: ""
          selector:
            duration:

mode: restart

variables:
  timer_entity_id: !input timer_entity
  trigger_states_input: !input trigger_states
  trigger_states_list: "{{ (trigger_states_input | string).split(',') | map('trim') | list }}"
  timer_duration_value: !input timer_duration

trigger:
  - platform: state
    entity_id: !input timer_entity
    from: idle
    to: active
    id: timer_active
  - platform: state
    entity_id: !input timer_entity
    to: idle
    id: timer_idle
  - platform: state
    entity_id: !input trigger_entities
    id: entity_triggered

condition:
  - condition: and
    conditions: !input global_conditions

action:
  - choose:
      # 1. Start/Restart Timer on activity
      - conditions:
          - condition: trigger
            id: entity_triggered
          - condition: template
            value_template: "{{ trigger.to_state.state in trigger_states_list }}"
          # Smart Logic: Only restart if idle OR new duration > remaining time.
          - condition: template
            value_template: >
              {% set t = timer_entity_id %}
              {% if states(t) == 'idle' %} true
              {% else %}
                {% set d_val = timer_duration_value if timer_duration_value else state_attr(t, 'duration') %}
                {% set d_sec = as_timedelta(d_val | string).total_seconds() if d_val else 0 %}
                {% set f = state_attr(t, 'finishes_at') %}
                {% set r_sec = (as_timestamp(f) - as_timestamp(now())) if f else 0 %}
                {{ d_sec > r_sec }}
              {% endif %}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ timer_duration_value != '' and timer_duration_value != none }}"
                sequence:
                  - action: timer.start
                    data:
                      entity_id: !input timer_entity
                      duration: !input timer_duration
            default:
              - action: timer.start
                data:
                  entity_id: !input timer_entity

      # 2. Turn Lights ON
      - conditions:
          - condition: trigger
            id: timer_active
          - condition: and
            conditions: !input turn_on_conditions
        sequence:
          - action: light.turn_on
            target: !input lights

      # 3. Turn Lights OFF
      - conditions:
          - condition: trigger
            id: timer_idle
          - condition: and
            conditions: !input turn_off_conditions
        sequence:
          - action: light.turn_off
            target: !input lights