blueprint:
  name: Timer-Based Lighting Automation (v2025.12.24.20.22)
  author: Dima Tokar
  source_url: https://github.com/dimatx/home-assistant/blob/main/blueprints/timer_driven_lighting_blueprint.yaml
  homeassistant:
    min_version: 2025.1.0
  description: >
    Automatically controls lights based on a timer and trigger entities.
    Supports targeting by Entities, Devices, Areas, and Labels.
  domain: automation
  input:
    timer_entity:
      name: Timer Entity
      selector:
        entity:
          domain: timer
    lights:
      name: Lights to Control
      selector:
        target:
          entity:
            domain: light
          device:
            filter:
              - domain: light
          area:
            filter:
              - domain: light
          label:
            filter:
              - domain: light
    trigger_entities:
      name: Trigger Entities
      selector:
        entity:
          multiple: true
    trigger_states:
      name: Trigger States
      default: "on"
      selector:
        text:
    timer_duration:
      name: Timer Duration (Optional)
      default: ""
      selector:
        duration:
    global_conditions:
      name: Global Conditions (Optional)
      default: []
      selector:
        condition:
    turn_on_conditions:
      name: Turn ON Conditions (Optional)
      default: []
      selector:
        condition:
    turn_off_conditions:
      name: Turn OFF Conditions (Optional)
      default: []
      selector:
        condition:

mode: restart

variables:
  trigger_states_input: !input trigger_states
  trigger_states_list: "{{ (trigger_states_input | string).split(',') | map('trim') | list }}"
  timer_duration_value: !input timer_duration

trigger:
  - platform: state
    entity_id: !input timer_entity
    from: idle
    to: active
    id: timer_active
  - platform: state
    entity_id: !input timer_entity
    to: idle
    id: timer_idle
  - platform: state
    entity_id: !input trigger_entities
    id: entity_triggered

condition:
  - condition: and
    conditions: !input global_conditions

action:
  - choose:
      - conditions:
          - condition: trigger
            id: entity_triggered
          - condition: template
            value_template: "{{ trigger.to_state.state in trigger_states_list }}"
        sequence:
          - action: timer.start
            data:
              entity_id: !input timer_entity
              duration: >
                {{ timer_duration_value if (timer_duration_value != '' and timer_duration_value != none) else skip }}

      - conditions:
          - condition: trigger
            id: timer_active
          - condition: and
            conditions: !input turn_on_conditions
        sequence:
          - action: light.turn_on
            target: !input lights

      - conditions:
          - condition: trigger
            id: timer_idle
          - condition: and
            conditions: !input turn_off_conditions
        sequence:
          - action: light.turn_off
            target: !input lights